[package]
name = "IntelligentNPCEcosystem"
version = "1.0.0"
authors = ["hackathon-team"]

[addresses]
npc_ecosystem = "_"

[dev-addresses]
npc_ecosystem = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"